/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/t2FzPqLEgx2
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useState } from "react"
import axios from "axios"

const getBackendUploadUrl = () => {
  if (import.meta.env.VITE_BACKEND_UPLOAD_URL) {
    return import.meta.env.VITE_BACKEND_UPLOAD_URL;
  }
  if (typeof window !== "undefined") {
    if (window.location.hostname !== "localhost" && window.location.hostname !== "127.0.0.1") {
      // Default to relative URL so Nginx reverse proxy routes /deploy and /status cleanly
      return "";
    }
  }
  return "http://localhost:3000";
};

const getRequestHandlerDomain = () => {
  let domain = import.meta.env.VITE_REQUEST_HANDLER_DOMAIN || "";
  
  if (!domain && typeof window !== "undefined" && window.location.hostname !== "localhost" && window.location.hostname !== "127.0.0.1") {
    const parts = window.location.hostname.split('.');
    if (parts.length >= 2) {
      domain = parts.slice(-2).join('.');
    } else {
      domain = window.location.hostname;
    }
  }
  
  if (!domain) {
    domain = "localhost:3001";
  }

  // If on a custom domain (non-localhost), strip port numbers like :3001 so wildcard Nginx routing matches
  if (typeof window !== "undefined" && window.location.hostname !== "localhost" && window.location.hostname !== "127.0.0.1") {
    domain = domain.split(':')[0];
  }
  
  return domain;
};

export function Landing() {
  const [repoUrl, setRepoUrl] = useState("");
  const [email, setEmail] = useState("");
  const [emailTouched, setEmailTouched] = useState(false);
  const [uploadId, setUploadId] = useState("");
  const [uploading, setUploading] = useState(false);
  const [deployed, setDeployed] = useState(false);
  const [failed, setFailed] = useState(false);

  const BACKEND_UPLOAD_URL = getBackendUploadUrl();
  const REQUEST_HANDLER_DOMAIN = getRequestHandlerDomain();
  
  // Format URL: Deployed preview sites use HTTP (http://<id>.ayushd785.dev) to match Nginx listen 80 wildcard block (*.ayushd785.dev)
  const deployedUrl = `http://${uploadId}.${REQUEST_HANDLER_DOMAIN}/index.html`;

  const isValidEmail = (val: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val);
  const emailError = emailTouched && email !== "" && !isValidEmail(email);

  return (
    <main className="flex flex-col items-center justify-center min-h-screen bg-gray-50 dark:bg-gray-900 p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="text-xl">Deploy your GitHub Repository</CardTitle>
          <CardDescription>Enter the URL of your GitHub repository to deploy it</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="github-url">GitHub Repository URL</Label>
              <Input 
                id="github-url"
                onChange={(e) => {
                  setRepoUrl(e.target.value);
                }} 
                placeholder="https://github.com/username/repo" 
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="notification-email">
                Notification Email{" "}
                <span style={{ color: "hsl(var(--muted-foreground))", fontWeight: 400, fontSize: "0.8em" }}>
                  (optional)
                </span>
              </Label>
              <Input 
                id="notification-email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                onBlur={() => setEmailTouched(true)}
                placeholder="you@example.com"
                style={emailError ? { borderColor: "hsl(var(--destructive))" } : {}}
              />
              {emailError && (
                <p style={{ color: "hsl(var(--destructive))", fontSize: "0.8rem", marginTop: "4px" }}>
                  Please enter a valid email address
                </p>
              )}
              {!emailError && email !== "" && isValidEmail(email) && (
                <p style={{ color: "#22c55e", fontSize: "0.8rem", marginTop: "4px" }}>
                  ✓ You'll receive build status notifications at this email
                </p>
              )}
            </div>
            <Button onClick={async () => {
              setUploading(true);
              setFailed(false);
              setDeployed(false);
              try {
                const res = await axios.post(`${BACKEND_UPLOAD_URL}/deploy`, {
                  repoUrl: repoUrl,
                  ...(email && isValidEmail(email) ? { email } : {})
                });
                setUploadId(res.data.id);
                setUploading(false);
                const interval = setInterval(async () => {
                  const response = await axios.get(`${BACKEND_UPLOAD_URL}/status?id=${res.data.id}`);

                  if (response.data.status === "deployed") {
                    clearInterval(interval);
                    setDeployed(true);
                  } else if (response.data.status === "failed") {
                    clearInterval(interval);
                    setFailed(true);
                  }
                }, 3000)
              } catch (err) {
                console.error("Deploy request failed:", err);
                setUploading(false);
                setFailed(true);
              }
            }} disabled={uploadId !== "" || uploading || emailError} className="w-full" type="submit">
              {uploadId ? `Deploying (${uploadId})` : uploading ? "Uploading..." : "Upload"}
            </Button>
          </div>
        </CardContent>
      </Card>
      {deployed && <Card className="w-full max-w-md mt-8">
        <CardHeader>
          <CardTitle className="text-xl">Deployment Status</CardTitle>
          <CardDescription>Your website is successfully deployed!</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            <Label htmlFor="deployed-url">Deployed URL</Label>
            <Input id="deployed-url" readOnly type="url" value={deployedUrl} />
          </div>
          <br />
          <Button className="w-full" variant="outline">
            <a href={deployedUrl} target="_blank" rel="noreferrer">
              Visit Website
            </a>
          </Button>
        </CardContent>
      </Card>}
      {failed && <Card className="w-full max-w-md mt-8 border-red-500">
        <CardHeader>
          <CardTitle className="text-xl text-red-500">Build Failed or Connection Error</CardTitle>
          <CardDescription>Could not complete deployment. Check repository or backend build logs.</CardDescription>
        </CardHeader>
      </Card>}
    </main>
  )
}
